version: '6.0'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.yml  
    container_name: resume_project
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    env_file:       
      - .env
    networks:
      - app-network

  db:
    image: postgres
    container_name: postgres
    restart: always
    tty: true
    ports:
      - "5433:5433" 
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
